service: titan-auth-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  profile: serverless

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate the api via Cognito User Pool. Update the 'arn'
  #     with your own User Pool ARN
  verify:
    handler: verify.handler
    memorySize: 128
    events:
      - http:
          path: api/auth/verify
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:765356211427:userpool/us-east-1_n0wdZW9H9
  login:
    handler: login.handler
    memorySize: 128
    events:
      - http:
          path: api/auth/login
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:765356211427:userpool/us-east-1_n0wdZW9H9
  create:
      handler: create.handler
      memorySize: 128
      events:
        - http:
            path: api/auth/create
            method: post
            cors: true
            authorizer:
              arn: arn:aws:cognito-idp:us-east-1:765356211427:userpool/us-east-1_n0wdZW9H9
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TitanAuth
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1